name: test
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
on:
  push: { branches: [ 'main' ] }
  pull_request: { types: [opened, reopened, synchronize, ready_for_review] }
  workflow_dispatch:
permissions:
  contents: read

jobs:
  linux-containerized-toplevel:
    strategy:
      fail-fast: false
      matrix:
        swift: 
          - swift:6.3-noble
          - swiftlang/swift:nightly-main-noble
    runs-on: ubuntu-latest
    container: ${{ matrix.swift }}
    steps:
      - run: apt-get update -y && apt-get install -y curl
      - uses: actions/checkout@v7
      - run: swift test --enable-code-coverage
      - uses: ./
        with:
          codecov_token: ${{ secrets.CODECOV_TOKEN }}
          dry_run: true
          verbose: true

  linux-containerized-subpath:
    strategy:
      fail-fast: false
      matrix:
        swift:
          - swift:6.3-noble
          - swiftlang/swift:nightly-main-noble
    runs-on: ubuntu-latest
    container: ${{ matrix.swift }}
    steps:
      - run: apt-get update -y && apt-get install -y curl
      - uses: actions/checkout@v7
      - run: swift test --package-path sample-coverage-data --enable-code-coverage
      - uses: ./
        with:
          codecov_token: ${{ secrets.CODECOV_TOKEN }}
          dry_run: true
          verbose: true
          package_path: sample-coverage-data

  macos-toplevel:
    runs-on: macos-26
    steps:
      - uses: maxim-lobanov/setup-xcode@ed7a3b1fda3918c0306d1b724322adc0b8cc0a90 # v1.7.0
        with: { xcode-version: latest-stable }
      - uses: actions/checkout@v7
      - run: swift test --enable-code-coverage
      - uses: ./
        with:
          codecov_token: ${{ secrets.CODECOV_TOKEN }}
          dry_run: true
          verbose: true

  macos-subpath:
    runs-on: macos-26
    steps:
      - uses: maxim-lobanov/setup-xcode@ed7a3b1fda3918c0306d1b724322adc0b8cc0a90 # v1.7.0
        with: { xcode-version: latest-stable }
      - uses: actions/checkout@v7
      - run: swift test --package-path sample-coverage-data --enable-code-coverage
      - uses: ./
        with:
          codecov_token: ${{ secrets.CODECOV_TOKEN }}
          dry_run: true
          verbose: true
          package_path: sample-coverage-data

  windows-toplevel:
    runs-on: windows-latest
    steps:
      - name: Install Windows Swift toolchain
        uses: compnerd/gha-setup-swift@397094e75494a93fa8d81db0268dbc8f5d6cf7c6 # v0.4.1
        with:
          swift-version: swift-6.3-release
          swift-build: 6.3-RELEASE
          update-sdk-modules: true
      - uses: actions/checkout@v7
      - run: |
          swift test --enable-code-coverage
      - uses: ./
        with:
          codecov_token: ${{ secrets.CODECOV_TOKEN }}
          dry_run: true
          verbose: true

  windows-subpath:
    runs-on: windows-latest
    steps:
      - name: Install Windows Swift toolchain
        uses: compnerd/gha-setup-swift@397094e75494a93fa8d81db0268dbc8f5d6cf7c6 # v0.4.1
        with:
          swift-version: swift-6.3-release
          swift-build: 6.3-RELEASE
          update-sdk-modules: true
      - uses: actions/checkout@v7
      - run: |
          swift test --package-path sample-coverage-data --enable-code-coverage
      - uses: ./
        with:
          codecov_token: ${{ secrets.CODECOV_TOKEN }}
          dry_run: true
          verbose: true
          package_path: sample-coverage-data
