name: test
on:
  push: { branches: [ 'main' ] }
  workflow_dispatch:

jobs:
  linux-containerized:
    runs-on: ubuntu-latest
    container: swift:5.5-focal
    steps:
      - uses: actions/checkout@v2
      - run: swift test --package-path sample-coverage-data --enable-code-coverage
      - uses: vapor/swift-codecov-action@fixups
        with:
          cc_dry_run: true
          cc_flags: unittests
          cc_env_vars: SWIFT_VERSION,SWIFT_SIGNING_KEY,SWIFT_PLATFORM,RUNNER_OS,RUNNER_ARCH
          cc_verbose: true
          package_path: sample-coverage-data

  macos:
    runs-on: macos-11
    steps:
      - uses: maxim-lobanov/setup-xcode@v1
        with: { xcode-version: latest }
      - uses: actions/checkout@v2
      - run: swift test --package-path sample-coverage-data --enable-code-coverage
      - uses: vapor/swift-codecov-action@fixups
        with:
          cc_dry_run: true
          cc_flags: unittests
          cc_env_vars: MD_APPLE_SDK_ROOT,RUNNER_OS,RUNNER_ARCH
          cc_verbose: true
          package_path: sample-coverage-data

  windows:
    runs-on: windows-latest
    steps:
      - uses: compnerd/gha-setup-swift@main
        with: { branch: 'swift-5.5.1-release', tag: '5.5.1-RELEASE' }
      - uses: actions/checkout@v2
      - run: swift test --package-path sample-coverage-data --enable-code-coverage
        shell: bash
      - run: env
        shell: bash
      - uses: vapor/swift-codecov-action@fixups
        with:
          cc_dry_run: true
          cc_flags: unittests
          cc_env_vars: RUNNER_OS,RUNNER_ARCH
          cc_verbose: true
          package_path: sample-coverage-data
